# Generated by Django 3.2.3 on 2021-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='critic',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
