# Generated by Django 3.2.3 on 2021-06-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
