# Generated by Django 3.2.3 on 2021-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_msuserprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecomments',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
