# Generated by Django 3.2.3 on 2021-06-02 18:16

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('desciption', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('ms_type', models.CharField(choices=[('S', 'Series'), ('M', 'Movies')], max_length=1)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('HR', 'Horror'), ('RO', 'Rommance'), ('DR', 'Drama'), ('CO', 'Comedy'), ('SC', 'Science-fiction'), ('DO', 'Documentry'), ('WE', 'Western'), ('MU', 'Musical')], max_length=2)),
                ('image', models.ManyToManyField(related_name='moveis', to='movies.Image')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
